cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/cask-versions'

brew 'ctags'
brew 'fzf'
brew 'git'
brew 'mobile-shell'
brew 'mosh'
brew 'neovim'
brew 'node'
brew 'rbenv'
brew 'rbenv-ctags'
brew 'rbenv-default-gems'
brew 'readline'
brew 'reattach-to-user-namespace'
brew 'ruby-build'
brew 'the_silver_searcher'
brew 'tig'
brew 'tmux'
brew 'vim'
brew 'youtube-dl'
brew 'zsh'

cask 'atom'
cask 'caffeine'
cask 'dash'
cask 'dropbox'
cask 'google-chrome'
cask 'google-chrome-canary'
cask 'whatsapp'
